# Generated by Django 4.2.6 on 2023-10-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-release_date'], 'verbose_name_plural': 'Movies'},
        ),
    ]
